config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'products#index'
  delete 'line_items/destroy_all/:id', to:'line_items#destroy_all', as: :line_items_destroy
  resources :line_items, only: [:index, :show, :create, :destroy]
  resources :carts, only: [:index, :show, :destroy]
  get 'products/grid'
  post 'products_search_path', to:'products#search', as: :products_search
  resources :products, only: [:index, :show, :destroy] do
    resources :comments, except: [:index,:show]
  end 
  resources :pianos
  resources :others
  resources :guitars 
  resources :drums
  resources :headphones
  get 'paypal/payment_success/:orderid', to:'orders#payment_success', as: :orders_payment_success
  get 'paypal/payment_cancel/:id', to:'orders#payment_cancel', as: :orders_payment_cancel
  resources :orders
  get 'application/logout'
  get 'application/cart'
  get 'settings/show'
  patch 'settings/change_avatar'
  patch 'settings/change_password'
  patch 'settings/change_mail'
  get 'activities/index'
  get 'admin_panel/show'
  delete 'admin_panel/ban'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
	# note : if we destroy the cart, we will destroy the line_items it contains
	has_many :line_items, dependent: :destroy


	# called in create line_item
	def add_product(product)
		item_to_add = line_items.find_by(product_id: product.id)
		if item_to_add
			item_to_add.quantity += 1
		else
			# in this case we create the line_item, the quantity default is 1
			item_to_add = line_items.build(product_id: product.id)
			item_to_add.order = nil
		end
		item_to_add
	end


	# total price of the cart
	def total
		prices = line_items.map {|li| li.price}
		prices.reduce(0) {|it0, it1| it0+it1}
	end


end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
 before_action :select_cart, only: [:show, :destroy]
 skip_before_action :verify_authenticity_token, :only => [:destroy]

def show 
end

def index
	if current_user != nil && current_user.admin
		@carts = Cart.all
	else
		invalid_cart
	end
end

def destroy
	if is_my_cart?(@cart)
		@cart.line_items.each do |li|
			li.delete_all_same_items
		end
		@cart.destroy 
		session[:cart_id] = nil
		redirect_to root_path, notice: "Cart emptied"
	else
		redirect_to root_path, alert: "Can't empty the selected cart"
	end
end


private 
	def select_cart
		@cart = Cart.find_by_id(params[:id])
		# can't access a cart which isn't in database
		# can't access the cart which doesn't correspond to my session if i'm not admin
		if @cart == nil || (@cart.id != session[:cart_id] && current_user != nil && current_user.admin != true)
			raise ActiveRecord::RecordNotFound
		end
		rescue ActiveRecord::RecordNotFound
			invalid_cart
	end

	def is_my_cart?(cart)
		if cart.id == session[:cart_id] || (current_user != nil && current_user.admin)
			return true
		end
		false
	end

	def invalid_cart
		redirect_to root_path, alert: 'Invalid cart'
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.haml
-# partial from cart, every time we render @cart this will be showed inline. So this can be rendered also in another view as a part of it 

%h2
	All items in cart 

%table.highlight
	%thead
		%tr
			%th
				Title
			%th
				Brand
			%th
				Model
			%th
				Quantity
			%th
				Price
			%th				
				
			%th
				
	%tbody
		-cart.line_items.each do |l_item|
			%tr
				= render l_item
				%td
					= link_to "Remove one", line_item_path(l_item.id), method: :delete 
				%td
					= link_to "Remove all", line_items_destroy_path(l_item.id), method: :delete

.cart-image
	= image_tag("cart.png", :alt => "Cart image")

%br
%br

%h4
	Total:
.cart-total
	= cart.total.to_s+" €"
.empty-cart
	= link_to "Empty cart", cart_path(cart.id), method: :delete
%br
.cart-checkout
	.waves-effect.waves-light.btn
		= link_to "Proceed to checkout", new_order_path

app/views/carts/show.html.haml
-# We render the partial _cart.html.haml  

= render (@cart)