config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'products#index'
  delete 'line_items/destroy_all/:id', to:'line_items#destroy_all', as: :line_items_destroy
  resources :line_items, only: [:index, :show, :create, :destroy]
  resources :carts, only: [:index, :show, :destroy]
  get 'products/grid'
  post 'products_search_path', to:'products#search', as: :products_search
  resources :products, only: [:index, :show, :destroy] do
    resources :comments, except: [:index,:show]
  end 
  resources :pianos
  resources :others
  resources :guitars 
  resources :drums
  resources :headphones
  get 'paypal/payment_success/:orderid', to:'orders#payment_success', as: :orders_payment_success
  get 'paypal/payment_cancel/:id', to:'orders#payment_cancel', as: :orders_payment_cancel
  resources :orders
  get 'application/logout'
  get 'application/cart'
  get 'settings/show'
  patch 'settings/change_avatar'
  patch 'settings/change_password'
  patch 'settings/change_mail'
  get 'activities/index'
  get 'admin_panel/show'
  delete 'admin_panel/ban'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
	# note : if we destroy the cart, we will destroy the line_items it contains
	has_many :line_items, dependent: :destroy


	# called in create line_item
	def add_product(product)
		item_to_add = line_items.find_by(product_id: product.id)
		if item_to_add
			item_to_add.quantity += 1
		else
			# in this case we create the line_item, the quantity default is 1
			item_to_add = line_items.build(product_id: product.id)
			item_to_add.order = nil
		end
		item_to_add
	end


	# total price of the cart
	def total
		prices = line_items.map {|li| li.price}
		prices.reduce(0) {|it0, it1| it0+it1}
	end


end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :product
    validates :title, presence: true
    validates_length_of :text, presence: true,:minimum => 1, :maximum => 500
    validates :user_id , uniqueness:{ scope:  :product_id , message: "You can only do a review"}
end

app/models/drum.rb
class Drum < ApplicationRecord
    validates :pedals, format: { with: /\A[1-2]\Z/, message: "1 or 2 pedals" }
    validates :cymbals, format: { with: /\A[1-9]\Z/, message: "1 to 9 cymbals" }
    validates :toms, format: {with: /\A[1-9]\Z/, message: "1 to 9 toms" }
    
    has_one :product, as: :instrum 	
	accepts_nested_attributes_for :product
end

app/models/guitar.rb
class Guitar < ApplicationRecord
    validates :hand, format: { with: /\A(Left)\Z|\A(Right)\Z/ }
    validates :chords, :numericality => {:greater_than => 0}
    has_one :product, as: :instrum 	
	accepts_nested_attributes_for :product
end

app/models/headphone.rb
class Headphone < ApplicationRecord
    has_one :product, as: :instrum 		# at every piano is associated a product
	accepts_nested_attributes_for :product
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :cart  #, optional: true
  belongs_to :product
  belongs_to :order, optional: true

  def delete_items
    self.product.quantity += 1
		self.product.save
  end
  
  def delete_all_same_items
    self.product.quantity += self.quantity
    self.product.save
  end

  def create_items
    self.product.quantity -= 1
    self.product.save
  end

  # this function checks if the buyer is also the owner, in which case
  # we destroy the line_item
  def ensure_buyer_isnt_the_owner(buyer)
    if buyer == product.user
      destroy
      raise RuntimeError
    end
  end

  def price
  	product.price*quantity
  end

end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	has_many :line_items

	validates :address, presence: true, length: { minimum:5 }
	validates :t_num, format: { with: /\A[0-9]{8,12}\Z/, message: "Insert a valid number" }
	validates :user_id, presence: true

	enum p_method: {
		"PayPal"	         => 0,
		"Cash on delivery"	 => 1
	}
	

	#add the items from the cart to the order
	def add_items_from_cart(cart)
		cart.line_items.each do |item|
			item.cart_id = nil
			line_items << item
		end
	end


end

app/models/other.rb
class Other < ApplicationRecord
	# validations
	validates :tipo, presence: true

	# associations
	has_one :product, as: :instrum		# at every other instrument is associated a product
	accepts_nested_attributes_for :product
end

app/models/piano.rb
class Piano < ApplicationRecord
	# validations 
	validates :tipo, presence: true, format: { with: /\A(A coda)|(A muro)|(Digitale)\Z/, message: "A coda, A muro o Digitale" }
	
	validates :n_keys, :numericality => {:greater_than => 0}

	# associations
	has_one :product, as: :instrum 		# at every piano is associated a product
	accepts_nested_attributes_for :product
end

app/models/product.rb
class Product < ApplicationRecord
	# validations
	validates :title, presence: true
	validates :price, presence: true, format: { with: /\A[0-9]{1,6}(.[0-9]{1,2})?\Z/, message: "Insert a valid price" }
	validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, message: "must be positive" }
	validates :weight, format: {with: /\A[0-9]{1,3}(.[0-9]{1,2})?\Z/, message: "Must be from 0 to 9999" }
	validates :height, format: {with: /\A[0-9]{0,4}\Z/, message: "Must be from 0 to 9999" }
	validates :length, format: {with: /\A[0-9]{0,4}\Z/, message: "Must be from 0 to 9999" }
	validates :depth, format: {with: /\A[0-9]{0,4}\Z/, message: "Must be from 0 to 9999" }
	validates :image, presence: true

	# associations
	has_many :comments , dependent: :destroy
	has_many :line_items
	belongs_to :user
	belongs_to :instrum, polymorphic: true

	class InvalidKeyError < RuntimeError
	end

	def self.walmart_key
		API_WALMART_KEY
	end

	#returns the price of the item found by model 
	#if item not found or model not specified, returns nil 
	def self.find_in_Walmart(model)
		return nil if model.blank?
		api_key = walmart_key
		raise InvalidKeyError if api_key.blank? 
		url = 'http://api.walmartlabs.com/v1/search?query='+ model + "&format=json&apiKey=#{api_key}"
		uri = URI(url)
		response = Net::HTTP.get(uri)
		parsed_resp = JSON.parse(response)
		raise InvalidKeyError if !parsed_resp["errors"].blank? && parsed_resp["errors"][0]["code"] == 403
		return nil if parsed_resp["items"].blank?
		return nil if ! /^Musical Instruments.*$/ .match? parsed_resp["items"][0]["categoryPath"] 
		parsed_resp["items"][0]["salePrice"]
	end


	private 
		# we need to check that when deleting a produc, it isn't referenced by a line_item
		# this is a hook method, automatically launched by rails when deletind a product
		def ensure_not_referenced_by_any_line_item
			unless line_items.empty?
				errors.add(:base, 'Line items reference this product')
				throw :abort
			end
		end
end

app/models/user.rb
class User < ApplicationRecord
  
  # associations 
  has_many :products, dependent: :destroy	# if we delete an user, we delete all his products too
  has_many :comments, dependent: :destroy
  has_many :orders

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:github]

	def self.from_omniauth(auth) 
	    where(provider: auth.provider, uid: auth.uid).first_or_create do |user| 
	      # NOTE: this is executed only at first login with oauht and sets
	      # the email associated to the github account as the following line specifies
	      user.email = auth.info.email || "#{auth.uid}@github.com"
	      #raise auth.info.inspect
	      user.password = Devise.friendly_token[0,20] 
	    end 
	end 
    
    def self.new_with_session(params, session) 
  	 	super.tap do |user| 
    		if data = session["devise.github_data"] && session["devise.github_data"]["extra"]["raw_info"] 
	      		user.email = data["email"] if user.email.blank? 
	    	end 
	 	end 
	end 


end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
	before_action :authenticate_user!

	def index
		@products = current_user.products
		@orders = current_user.orders
	end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/drums_helper.rb
module DrumsHelper
end

app/helpers/guitars_helper.rb
module GuitarsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/others_helper.rb
module OthersHelper
end

app/helpers/pianos_helper.rb
module PianosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/activities/index.html.haml
%div{ :class => "center"}
	%h3
		Sell another instrument:
	%br
	%div{ :class => "collection new-collection" }
		= link_to "Sell Piano",new_piano_path, :class => "collection-item"
		
		= link_to "Sell generic item",new_other_path, :class => "collection-item"
		
		= link_to "Sell Guitar or Bass",new_guitar_path, :class => "collection-item"
		
		= link_to "Sell Drum",new_drum_path, :class => "collection-item"
		
		= link_to "Sell Headphone",new_headphone_path, :class => "collection-item"

	%h3
		Your products for sale:
	%br
		%ul{ :class => "collection" }
			- @products.each do |prod|	
				-if prod.instrum.instance_of?(Piano)
					%div{ :id => prod.title }
						%li{ :class => "collection-item" }
							%div{:class => "text-size"}
								= prod.title
								= link_to piano_path(prod.instrum),method: :delete, data: {confirm: "Are you sure?"}, :class => "secondary-content" do
									%i{ :class => "material-icons" }
										delete
								= link_to edit_piano_path(prod.instrum), id: "modify-#{prod.title}",:class => "secondary-content" do
									%i{ :class => "material-icons" }
										edit
					
				-if prod.instrum.instance_of?(Other)
					%div{ :id => prod.title }
						%li{ :class => "collection-item" }
							%div{:class => "text-size"}
								= prod.title
								= link_to other_path(prod.instrum),method: :delete, data: {confirm: "Are you sure?"}, :class => "secondary-content" do
									%i{ :class => "material-icons" }
										delete
								= link_to edit_other_path(prod.instrum),:class => "secondary-content" do
									%i{ :class => "material-icons" }
										edit
					
				-if prod.instrum.instance_of?(Guitar)
					%div{ :id => prod.title }
						%li{ :class => "collection-item" }
							%div{:class => "text-size"}
								= prod.title
								= link_to guitar_path(prod.instrum),method: :delete, data: {confirm: "Are you sure?"}, :class => "secondary-content" do
									%i{ :class => "material-icons" }
										delete
								= link_to edit_guitar_path(prod.instrum),:class => "secondary-content" do
									%i{ :class => "material-icons" }
										edit
		
				-if prod.instrum.instance_of?(Drum)
					%div{ :id => prod.title }
						%li{ :class => "collection-item" }
							%div{:class => "text-size"}
								= prod.title
								= link_to drum_path(prod.instrum),method: :delete, data: {confirm: "Are you sure?"}, :class => "secondary-content" do
									%i{ :class => "material-icons" }
										delete
								= link_to edit_drum_path(prod.instrum),:class => "secondary-content" do
									%i{ :class => "material-icons" }
										edit
					
				-if prod.instrum.instance_of?(Headphone)
					%div{ :id => prod.title }
						%li{ :class => "collection-item" }
							%div{:class => "text-size"}
								= prod.title
								= link_to headphone_path(prod.instrum),method: :delete, data: {confirm: "Are you sure?"}, :class => "secondary-content" do
									%i{ :class => "material-icons" }
										delete
								= link_to edit_headphone_path(prod.instrum),:class => "secondary-content" do
									%i{ :class => "material-icons" }
										edit
	%h3
		Your Orders:
	%br
		%div{ :class => "collection" }
			-@orders.each do |order|
				= link_to order.id , order_path(order), :class => "collection-item"