config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'products#index'
  delete 'line_items/destroy_all/:id', to:'line_items#destroy_all', as: :line_items_destroy
  resources :line_items, only: [:index, :show, :create, :destroy]
  resources :carts, only: [:index, :show, :destroy]
  get 'products/grid'
  post 'products_search_path', to:'products#search', as: :products_search
  resources :products, only: [:index, :show, :destroy] do
    resources :comments, except: [:index,:show]
  end 
  resources :pianos
  resources :others
  resources :guitars 
  resources :drums
  resources :headphones
  get 'paypal/payment_success/:orderid', to:'orders#payment_success', as: :orders_payment_success
  get 'paypal/payment_cancel/:id', to:'orders#payment_cancel', as: :orders_payment_cancel
  resources :orders
  get 'application/logout'
  get 'application/cart'
  get 'settings/show'
  patch 'settings/change_avatar'
  patch 'settings/change_password'
  patch 'settings/change_mail'
  get 'activities/index'
  get 'admin_panel/show'
  delete 'admin_panel/ban'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	# validations
	validates :title, presence: true
	validates :price, presence: true, format: { with: /\A[0-9]{1,6}(.[0-9]{1,2})?\Z/, message: "Insert a valid price" }
	validates :quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, message: "must be positive" }
	validates :weight, format: {with: /\A[0-9]{1,3}(.[0-9]{1,2})?\Z/, message: "Must be from 0 to 9999" }
	validates :height, format: {with: /\A[0-9]{0,4}\Z/, message: "Must be from 0 to 9999" }
	validates :length, format: {with: /\A[0-9]{0,4}\Z/, message: "Must be from 0 to 9999" }
	validates :depth, format: {with: /\A[0-9]{0,4}\Z/, message: "Must be from 0 to 9999" }
	validates :image, presence: true

	# associations
	has_many :comments , dependent: :destroy
	has_many :line_items
	belongs_to :user
	belongs_to :instrum, polymorphic: true

	class InvalidKeyError < RuntimeError
	end

	def self.walmart_key
		API_WALMART_KEY
	end

	#returns the price of the item found by model 
	#if item not found or model not specified, returns nil 
	def self.find_in_Walmart(model)
		return nil if model.blank?
		api_key = walmart_key
		raise InvalidKeyError if api_key.blank? 
		url = 'http://api.walmartlabs.com/v1/search?query='+ model + "&format=json&apiKey=#{api_key}"
		uri = URI(url)
		response = Net::HTTP.get(uri)
		parsed_resp = JSON.parse(response)
		raise InvalidKeyError if !parsed_resp["errors"].blank? && parsed_resp["errors"][0]["code"] == 403
		return nil if parsed_resp["items"].blank?
		return nil if ! /^Musical Instruments.*$/ .match? parsed_resp["items"][0]["categoryPath"] 
		parsed_resp["items"][0]["salePrice"]
	end


	private 
		# we need to check that when deleting a produc, it isn't referenced by a line_item
		# this is a hook method, automatically launched by rails when deletind a product
		def ensure_not_referenced_by_any_line_item
			unless line_items.empty?
				errors.add(:base, 'Line items reference this product')
				throw :abort
			end
		end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!, except: [:index,:show,:grid,:search]
    # to allow delete request
    skip_before_action :verify_authenticity_token, :only => [:destroy]


    def index
        @products = Product.all
        if params[:brand] && params[:brand] != ""
            @products = Product.where('brand LIKE?', "%#{params[:brand]}%")
        end
        if params[:model] && params[:model] != ""
            @products = @products.select {|p| p.model == params[:model] }
        end
        if params[:min_price] && params[:min_price] != ""
            @products = @products.select {|p| p.price >= params[:min_price].to_f}
        end
        if params[:max_price] && params[:max_price] != ""
            @products = @products.select {|p| p.price <= params[:max_price].to_f}
        end
    end

    def show
        @product = Product.find_by_id(params[:id])
        @comment = Comment.new
        if @product == nil then
            redirect_to products_path, notice: "The product selected doesn't belong to the list"
        end     
    end
    
    def destroy
        @product = Product.find(params[:id])  
        if @product.user == current_user || current_user.admin?
            @product.instrum.destroy
            @product.destroy
            redirect_to products_path
        else
            flash.keep[:notice] = "You can't delete this item"
        end
    end

    def search 
        match_string = params[:search]
        @products = Product.where('title LIKE?', "%#{match_string}%")
        render :index
    end

        private 
        
            def products_params
                params.require(:product).permit(title,:brand,:model,:price,:quantity,:weight,:description,:image,:term,:s_price)
            end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
      <div class="note">
        All required fields are signed with bold font and red color.
      </div>
      <div class="row">
        <div class="input-field col s6">
            <div class="required">
              <%= f.label :title , :class => "active" %>
              <%= f.text_field :title %>
            </div>
        </div>
      </div>

      <div class="row">
        <div class="input-field col s6">
            <%= f.label :brand , :class => "active" %>
            <%= f.text_field :brand %>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
            <%= f.label :model , :class => "active" %>
            <%= f.text_field :model %>
        </div>
      </div>
      <div class="file-field input-field col s12 m8">
        <div class="btn">
          <span>File</span>
            <%= f.file_field :image %>
        </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text">
        </div>
      </div>
      <div class="block-container">
        <div class="block-form-small">
          <div class="row">
            <div class="input-field col s6">
                <div class="required">
                  <%= f.label :price , :class => "active" %>
                  <%= f.number_field :price , :step => "0.01" %>
                </div>
                <%- if @instrum.present? && @instrum.product.price.present? && @wal_price.present? && @wal_price < @instrum.product.price then%>
                  <div class="wal-price">
                    Lower price on Walmart: <%= @wal_price %>
                  </div>
                <% end %>
            </div>
          </div>
        </div>
        <div class="block-form-small">
          <div class="row">
            <div class="input-field col s6">
                <div class="required">
                  <%= f.label :quantity , :class => "active" %>
                  <%= f.number_field :quantity %>
                </div>
             </div>
          </div>
        </div>
      </div>
      <div class="block-form-small">
        <div class="row">
          <div class="input-field col s6">
            <div class="required">
              <%= f.label :weight , :class => "active" %>
              <%= f.number_field :weight %>
            </div>
          </div>
        </div>
      </div>
      <div class="block-form-small">
        <div class="row">
          <div class="input-field col s6">
              <%= f.label :height , :class => "active" %>
              <%= f.number_field :height %>
          </div>
        </div>
      </div>
      <div class="block-form-small">
        <div class="row">
          <div class="input-field col s6">
              <%= f.label :length , :class => "active" %>
              <%= f.number_field :length %>
          </div>
        </div>
      </div>
      <div class="block-form-small">
        <div class="row">
          <div class="input-field col s6">
              <%= f.label :depth , :class => "active" %>
              <%= f.number_field :depth %>
          </div>
        </div> 
      </div>
      <div class="input-field col s9">
            <%= f.label :description , :class => "active" %>
            <%= f.text_area :description, :class => "materialize-textarea" %>
      </div>

app/views/products/_product.html.erb
<!--# partial from product, every time we render @product this will be showed inline. So this can be rendered also in another view as a part of it -->


<div class="show-card-height col s12 m7"> 
    <div class="card horizontal">      
      <div class="card-image">
        <%= image_tag "data:image/jpeg;base64,#{product.image}", :class => 'product-image' %>
      </div>
      <div class="card-stacked">
        <h2 class="header-title"><%= product.title %></h2>
        <div class="show-card card-content">
          <div class="field-title">
            Description:
          </div>
          <div class="field-content">
            <p><%= product.description %></p>
          </div>
          <%-if product.height || product.length || product.depth || product.weight  %>
          <table>
            <thead>
              <tr>
                <th>Height</th>
                <th>Lenght</th>
                <th>Depth</th>
                <th>Weight</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td class="field-content"><%-if product.height  %>
                      <%= product.height.to_s+" cm"%>
                    <%- end %>
                </td>
                <td class="field-content"><%-if product.length  %>
                      <%= product.length.to_s+" cm"%>
                    <%- end %>
                </td>
                <td class="field-content"><%-if product.depth  %>
                      <%= product.depth.to_s+" cm"%>
                    <%- end %>
                </td>
                <td class="field-content"><%-if product.weight  %>
                      <%= product.weight.to_s+" kg"%>
                    <%- end %>
                </td>
              </tr>
            </tbody>
          </table>
          <%- end %>
        <%- if !product.brand.blank? %>
          <div class="field-title">
            Brand:
          </div>
          <div class="field-content">
            <%= product.brand %>  
          </div>
        <% end %>
        <%- if !product.model.blank? %>
          <div class="field-title">
            Model:
          </div>
          <div class="field-content">
            <%= product.model%>
          </div>
        <% end %>
        <%- if !product.quantity.blank? %>
          <div class="field-title">
            Quantity:
          </div>
          <div class="field-content">
            <%= product.quantity%>
          </div>
        <% end %>
        </div>
        <div class="header">
          <span class="field-title">
            Seller:
          </span>
          <%= product.user.email %>
        </div>
        <div class="show-card-btn card-action">
          <span class="field-title">
            Price:
          </span>
          <span class="show-price"><%= product.price %>  € </span>
          <span class= "buttons">
            <%- if current_user != product.user then %>
            <%= link_to "Buy", line_items_path(product_id: product), method: :post %>
            <%- end %>
            <%- if current_user == product.user || (current_user != nil && current_user.admin? ) then %>
              <%= link_to "Remove", product_path(product), method: :delete %>
            <%-end %>
          </span>
        </div>
      </div>
    </div>
  </div>

app/views/products/edit.html.erb
<%= link_to product_path(@product) do %>

    <i class="material-icons">arrow_back</i> Back
  </div>
<% end %>

<%= render  "form" %>

app/views/products/grid.html.erb
  <div class="row" id="grid-head">
    <div class="col s12 m6">
      <div class="grid-element">
        <div class="card">
          <div class="card-image">
            <%= link_to image_tag("pianos.jpg", :alt => "Pianos"), pianos_path %>
            <span class="card-title">Pianos</span>
            <a class="btn-floating halfway-fab waves-effect waves-light red" href="/pianos/new"><i class="material-icons">add</i></a>
          </div>
          <div class="card-content">
            <p>Here you can find all the offers about pianos, digital or acoustics, upright pianos or grand pianos with relative image</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row" id="grid-head">
   <div class="col s12 m6">
    <div class="grid-element">
      <div class="card">
        <div class="card-image">
          <%= link_to image_tag("guitars.jpg", :alt => "Others"), guitars_path %>
          <span class="card-title">Guitars and basses</span>
          <a class="btn-floating halfway-fab waves-effect waves-light red" href="/guitars/new"><i class="material-icons">add</i></a>
          </div>
          <div class="card-content">
            <p>Here you can find all the offers about guitars and basses, divided in left and right handed but also in digitals and acoustics</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row" id="grid-head">
   <div class="col s12 m6">
    <div class="grid-element">
      <div class="card">
        <div class="card-image">
          <%= link_to image_tag("drums.jpg", :alt => "Others"), drums_path %>
          <span class="card-title">Drums</span>
          <a class="btn-floating halfway-fab waves-effect waves-light red" href="/drums/new"><i class="material-icons">add</i></a>
          </div>
          <div class="card-content">
            <p>Here you can find all the offers about drums, selected by price but also by number of pedals and cymbals</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row" id="grid-head">
   <div class="col s12 m6">
    <div class="grid-element">
      <div class="card">
        <div class="card-image">
          <%= link_to image_tag("headphones.jpg", :alt => "Others"), headphones_path %>
          <span class="card-title">Headphones and microphones</span>
          <a class="btn-floating halfway-fab waves-effect waves-light red" href="/headphones/new"><i class="material-icons">add</i></a>
          </div>
          <div class="card-content">
            <p>Here you can find all the offers about headphones and microphones, and chose the one that you prefer according to many tecnical characteristics</p>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row" id="grid-head">
   <div class="col s12 m6">
    <div class="grid-element">
      <div class="card">
        <div class="card-image">
          <%= link_to image_tag("others.jpg", :alt => "Others"), others_path %>
          <span class="card-title">Others</span>
          <a class="btn-floating halfway-fab waves-effect waves-light red" href="/others/new"><i class="material-icons">add</i></a>
          </div>
          <div class="card-content">
            <p>Here you can find all the offers about all the instruments who doesn't belong to one of the previous categories. For example violins, saxophones ecc...</p>
          </div>
        </div>
      </div>
    </div>
  </div>
          

app/views/products/index.html.erb
<h3>Instruments</h3>
<div class="row">
  <% @products.each do |prod| %>
    <% if prod.quantity > 0 %>
      <div class="col s6 m3 l2" id="prod-<%= prod.title %>">
        <div class="card medium">
          <div class="card-content">
            <div class="card-title"><%= prod.title %></div>
          </div>
          <div class="index-card-image card-image">
            <%= image_tag "data:image/jpeg;base64,#{prod.image}"%>
          </div>
          
          <div class="card-action card-price">
            <%= link_to  "Details", product_path(prod), id: "link-#{prod.id}" %>
            <%= prod.price %>  € 
          </div>
        </div>
      </div>
    <% end %>
  <% end %> 
</div>

app/views/products/new.html.erb
<%= link_to products_path do %>

    <i class="material-icons">arrow_back</i> Back
  </div>
<% end %>

<%= render  "form" %>

app/views/products/show.html.erb
<!-- We render the partial _product.html.haml
	 and the partial _instrum associated -->
<%= render(@product) %>
<%= render(@product.instrum) %>
<div class="comments">
	<% if @product.user != current_user && @product.comments.where(:user => current_user).size == 0 && user_signed_in?%>
		<%= render  "comments/form" %>
	<% end %>

	<h2 class="comments-head"> Comments </h2>
	<% if !@product.comments.nil? %>
		<% @product.comments.each  do |comm| %>
			<%= render(comm) %>
		<% end %>
	<% end %>

</div>